export const DISPLAY_BLOG_USERS_REQUEST = "DISPLAY_BLOG_USERS_REQUEST"
export const DISPLAY_BLOG_USERS_SUCCESS = "DISPLAY_BLOG_USERS_SUCCESS"
export const DISPLAY_BLOG_USERS_FAILURE = "DISPLAY_BLOG_USERS_FAILURE"
