export const CREATEBLOG_USERS_REQUEST = "CREATEBLOG_USERS_REQUEST"
export const CREATEBLOG_USERS_SUCCESS = "CREATEBLOG_USERS_SUCCESS"
export const CREATEBLOG_USERS_FAILURE = "CREATEBLOG_USERS_FAILURE"
