export const LIKE_DELIKE_BLOG_REQUEST = "LIKE_DELIKE_BLOG_REQUEST";
export const LIKE_DELIKE_BLOG_SUCCESS = "LIKE_DELIKE_BLOG_SUCCESS";
export const LIKE_DELIKE_BLOG_FAILURE = "LIKE_DELIKE_BLOG_FAILURE";
